accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article_like/<int:pk>', LikeArticleView.as_view(), name="article_like")
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path("admin/", admin.site.urls),
    path("accounts/", include('accountapp.urls')),
    path("profiles/", include('profileapp.urls')),
    path("articles/", include('articleapp.urls')),
    path("comments/", include('commentapp.urls')),
    path("projects/", include('projectapp.urls')),
    path("subscribe/", include('subscribeapp.urls')),
    path("likes/", include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView, ProjectDeleteView

app_name = 'projectapp'

urlpatterns = [
    path('list', ProjectListView.as_view(), name='list'),

    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

    path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load bootstrap4 %}
{% include 'head.html' %}
{% bootstrap_css %}
<body style="font-family:'NanumSquare'">

    {% include 'header.html' %}

    <hr/>

    {% if messages %}
    {% for message in messages %}
    <div style="text-align: center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5 my-3">
            {{ message }}
        </div>
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    <hr/>

    {% include 'footer.html' %}
{% bootstrap_javascript jquery='full' %}
</body>
</html>

templates/footer.html
    <div class="pragmatic_footer">
        <div class="pragmatic_footer_button">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스소개</span>
        </div>
        <div>
            <h6 class="pragmatic_footer_logo">Pinterest</h6>
        </div>
    </div>

templates/head.html
    {% load static %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Pinterest App</title>


        <!--  BOOTSTRAP LINK  -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
              integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

        <!--  GOOGLE FONTS LINK  -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

        <!--  GOOGLE MATERIAL ICONS  -->
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

        <!--  DEFAULT CSS LINK  -->
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

        <!-- Nanum font link -->
        <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
        <style>
            @font-face {
                font-family: 'NanumSquareLight';
            }
            @font-face {
                font-family: 'NanumSquare';
            }
            @font-face {
                font-family: 'NanumSquareBold';
            }
            @font-face {
                font-family: 'NanumSquareExtraBold';
            }
        </style>
    </head>

templates/header.html
<style>
a {
    color: black;
}

a:hover {
    color: black;
    text-decoration: none;
}

.pragmatic_header_nav {
    margin: 0 0.5rem;
}

.pragmatic_header_navbar {
    margin: 1rem 0;
}

</style>


    <div class="pragmatic_header">
        <div>
            <h1 class="pragmatic_logo">
                <a href="{% url 'home' %}" class="pragmatic_header_nav">
                    Pinterest
                </a>
            </h1>
        </div>
        <div class="pragmatic_header_navbar">
            <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
                <span>Article</span>
            </a>
            <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
                <span>Gallery</span>
            </a>
            <a href="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
                <span>Subscription</span>
            </a>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
                <span>login</span>
            </a>
            <a href="{% url 'accountapp:create' %}" class="pragmatic_header_nav">
                <span>SignUp</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="pragmatic_header_nav">
                <span>MyPage</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="pragmatic_header_nav">
                <span>logout</span>
            </a>
            {% endif %}
        </div>
    </div>