accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article_like/<int:pk>', LikeArticleView.as_view(), name="article_like")
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path("admin/", admin.site.urls),
    path("accounts/", include('accountapp.urls')),
    path("profiles/", include('profileapp.urls')),
    path("articles/", include('articleapp.urls')),
    path("comments/", include('commentapp.urls')),
    path("projects/", include('projectapp.urls')),
    path("subscribe/", include('subscribeapp.urls')),
    path("likes/", include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.
class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now=True, null=True)

    like = models.IntegerField(default=0)

articleapp/forms.py
from django.forms import ModelForm
from django import forms

from articleapp.models import Article
from projectapp.models import Project


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'rows': 5,
                                                           'style': 'height: auto;'}))
    project = forms.ModelChoiceField(queryset=Project.objects.all(),
                                     initial=0,
                                     required=False)
    class Meta:
        model = Article
        fields = ['title', 'project', 'image', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


# Create your views here.
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 25

articleapp/templates/articleapp/create-1.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}


</style>

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Create Article</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                {% for field in form %}
                <div class="mb-3">
                    {{ field.errors }}
                    {{ field.label_tag }}</span> {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Create Article</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Delete Article : {{ target_article.title }} ({{ target_article.pk }})</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 700px; margin: 4rem auto;">

        <h2>
            <strong>{{ target_article.title }}</strong>
        </h2>
        <div style="height: 2rem">
            <a href="{% url 'likeapp:article_like' pk=target_article.pk %}">
            <i style="vertical-align: middle; font-size: 1.2rem; color: #f77"
               class="material-icons">
                favorite
            </i>
            </a>
            <span style="vertical-align: middle; font-size: 1.2rem;">
                {{ target_article.like }}
            </span>
        </div>
        <div>
            <img src="{{ target_article.writer.profile.image.url }}" alt="profile"
                 style="height: 3rem; width: 3rem; border-radius: 20rem; margin-bottom: 1rem; object-fit: cover;">
            <h5>
                {{ target_article.writer.profile.nickname }} &nbsp;&nbsp;&nbsp;{{ target_article.created_at }}
            </h5>
        </div>

        <hr/>
        <img src="{{ target_article.image.url }}" alt="" style="width:100%; border-radius: 1rem; margin: 2rem 0">
        <div class="text-left mb-5">
            {{ target_article.content | safe }}
        </div>

        {% if user.is_authenticated %}
        <a href="{% url 'articleapp:create' %}" class="btn btn-primary rounded-pill col-3">
            Create
        </a>
        {% else %}
        <a href="{% url 'accountapp:login' %}" class="btn btn-primary rounded-pill col-3">
            Login
        </a>
        {% endif %}
        {% if target_article.writer == request.user %}
        <a href="{% url 'articleapp:update' pk=target_article.pk %}" class="btn btn-primary rounded-pill col-3">
            Update
        </a>
        <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-danger rounded-pill col-3">
            Delete
        </a>
        {% endif %}

        <hr/>

        {% for comment in target_article.comment.all %}
            {% include 'commentapp/detail.html' with comment=comment %}
        {% endfor %}

        {% include 'commentapp/create.html' with article=target_article %}

    </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>

    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
      width: 40%;
      max-width: 250px;
    }

    .container div {
      display: flex;
      justify-content: center;
      align-items: center;

      border-radius: 1rem;
    }

    .container img {
      width: 100%;
      border-radius: 1rem;
    }

</style>
    {% if article_list %}
    <div class="container">
        {% for article in article_list %}
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
            {% include 'snippets/card.html' with article=article %}
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
    <div class="text-center">
        <h1>No Articles YET!</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
            Create Article
        </a>
    </div>



{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Article Update</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}